version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ${APP_NAME}-app
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    image: ${APP_NAME}-nginx
