version: "3.7"

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    image: tatami-php
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    image: tatami-nginx
