version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile  
    image: ${APP_NAME}-app
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    networks:
      - ${APP_NAME}-lemp

  db:
    image: mysql:5.7.10
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_PASSWORD}'
      MYSQL_PASSWORD: '${DB_USERNAME}'
    ports:
      - "3306:3306"
    # volumes:
    #   - ./config/mysql:/docker-entrypoint-initdb.d
    networks:
      - ${APP_NAME}-lemp
      
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: '${DB_DATABASE}'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - ${APP_NAME}-lemp         

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - tatami-lemp       

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    image: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ${APP_NAME}-lemp
    depends_on:
      - app
networks:
  tatami-lemp:
    driver: bridge
