version: "3.7"
services:
  php:
    image: ${APP_NAME}-php:latest
    restart: unless-stopped
    networks:
      - ${APP_NAME}-lemp
  nginx:
    image: ${APP_NAME}-nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - ${APP_NAME}-lemp
    depends_on:
      - php      

networks:
  tatami-lemp:
    driver: bridge
volumes:
  app_volume: null
