version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile  
    image: ${APP_NAME}-app
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    networks:
      - tatami-lemp      

  db:
    image: mysql/mysql-server:5.7.10
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
    ports:
      - "3306:3306"
    volumes:
    #   - ./config/mysql:/docker-entrypoint-initdb.d
      - 'storage_mysql:/var/lib/mysql:rw'
    networks:
      - tatami-lemp

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: 'db'
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - tatami-lemp
    depends_on:
      - db

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - tatami-lemp       

  nginx:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tatami-lemp
    depends_on:
      - app

networks:
  tatami-lemp:
    driver: bridge
volumes:
  storage_mysql: null