version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: ./docker-config/php/Dockerfile
      args:
        PUBLIC_PATH: ${PUBLIC_PATH:-./app}     
    image: ${APP_NAME}-app
    restart: unless-stopped
    volumes:
      - ${PUBLIC_PATH:-./app}:/var/www/html
    networks:
      - tatami-lemp  
    depends_on:
      - mysql      

  mysql:
    image: mysql/mysql-server:5.7.10
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1      
    ports:
      - "3306:3306"
    volumes:
    #   - ./config/mysql:/docker-entrypoint-initdb.d
      - 'tatami-mysql:/var/lib/mysql:rw'
    networks:
      - tatami-lemp

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: '${DB_HOST}'
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - tatami-lemp
    depends_on:
      - mysql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - tatami-lemp       

  nginx:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${PUBLIC_PATH:-./app}:/var/www/html
      - ./docker-config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-config/nginx/${NGINX_CONF:-default}.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tatami-lemp
    depends_on:
      - app

networks:
  tatami-lemp:
    driver: bridge
volumes:
  tatami-mysql: 
    driver: local