version: "3.7"
services:
  php:
    image: tatami-php:latest
    restart: unless-stopped
    networks:
      - tatami-lemp
  nginx:
    image: tatami-nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - tatami-lemp
    depends_on:
      - php      

networks:
  tatami-lemp:
    driver: bridge
volumes:
  app_volume: null
