name: Docker Image CI

on: workflow_dispatch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  just-a-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello Actions"

  # build:
  #   runs-on: ubuntu-latest
    
    # steps:
    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
