name: Build Tatami

on: workflow_dispatch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Building the image
        run: |
          docker build . --file docker-config/base/Dockerfile --tag tatami-lemp:2

      - name: Log into GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin          

      - name: Push image to Github Container Registry
        run: |
          docker tag tatami-lemp:2 ghcr.io/${{ github.repository_owner }}/tatami-lemp:2
          docker push ghcr.io/${{ github.repository_owner }}/tatami-lemp:2